repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^packages/backend/
      - id: ruff-format
        files: ^packages/backend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^packages/backend/src/
        additional_dependencies:
          - types-redis
          - types-pyyaml
          - types-requests
        args: [--ignore-missing-imports, --no-strict-optional]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.0
    hooks:
      - id: eslint
        files: ^packages/(frontend|shared)/
        types: [file]
        types_or: [javascript, jsx, ts, tsx]
        args: [--fix]
        additional_dependencies:
          - eslint@^8.57.1
          - eslint-config-next@14.2.5
          - '@typescript-eslint/eslint-plugin@^6.0.0'
          - '@typescript-eslint/parser@^6.0.0'
