"""Setup script for the TradingAgents backend package."""

from setuptools import find_packages, setup

setup(
    name="tradingagents",
    version="0.1.0",
    description="Multi-Agents LLM Financial Trading Framework",
    author="TradingAgents Team",
    author_email="yijia.xiao@cs.ucla.edu",
    url="https://github.com/TauricResearch",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    include_package_data=True,
    package_data={
        "cli": ["static/*.txt"],
    },
    install_requires=[
        "akshare>=1.16.98",
        "alembic>=1.13.0",
        "asyncpg>=0.29.0",
        "aiosqlite>=0.20.0",
        "backtrader>=1.9.78.123",
        "chainlit>=2.5.5",
        "chromadb>=1.0.12",
        "eodhd>=1.0.32",
        "feedparser>=6.0.11",
        "finnhub-python>=2.4.23",
        "grip>=4.6.2",
        "langchain-anthropic>=0.3.15",
        "langchain-experimental>=0.3.4",
        "langchain-google-genai>=2.1.5",
        "langchain-openai>=0.3.23",
        "langgraph>=0.4.8",
        "pandas>=2.3.0",
        "parsel>=1.10.0",
        "praw>=7.8.1",
        "pydantic-settings>=2.0.0",
        "pytz>=2025.2",
        "pyyaml>=6.0.2",
        "questionary>=2.1.0",
        "python-dotenv>=1.0.1",
        "redis>=6.2.0",
        "requests>=2.32.4",
        "rich>=14.0.0",
        "setuptools>=80.9.0",
        "sqlmodel>=0.0.22",
        "stockstats>=0.6.5",
        "tqdm>=4.67.1",
        "tushare>=1.4.21",
        "typing-extensions>=4.14.0",
        "yfinance>=0.2.63",
    ],
    python_requires=">=3.10",
    entry_points={
        "console_scripts": [
            "tradingagents=cli.main:app",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Trading Industry",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Topic :: Office/Business :: Financial :: Investment",
    ],
)
