"""Pydantic models shared across API routes."""

from .agent_config import (
    AgentConfigBase,
    AgentConfigCreate,
    AgentConfigList,
    AgentConfigResponse,
    AgentConfigUpdate,
)
from .auth import (
    APIKeyCreate,
    APIKeyResponse,
    AuditLogResponse,
    PasswordChange,
    Token,
    TokenRefresh,
    UserCreate,
    UserLogin,
    UserResponse,
    UserUpdate,
)
from .backtest import (
    BacktestArtifactResponse,
    BacktestComparisonEntry,
    BacktestComparisonResponse,
    BacktestComparisonSummary,
    BacktestDecisionLogEntry,
    BacktestEquityPointResponse,
    BacktestExportResponse,
    BacktestMetricsResponse,
    BacktestParameters,
    BacktestRunDetailResponse,
    BacktestRunResponse,
    BacktestTradeLogEntry,
    StartBacktestRequest,
)
from .trading import (
    ExecuteSignalRequest,
    ForceExitRequest,
    PortfolioStateDetailResponse,
    PortfolioStateResponse,
    PositionResponse,
    RiskDiagnosticsResponse,
    StartSessionRequest,
    TradeResponse,
    TradingSessionResponse,
)

__all__ = [
    "AgentConfigBase",
    "AgentConfigCreate",
    "AgentConfigUpdate",
    "AgentConfigResponse",
    "AgentConfigList",
    "APIKeyCreate",
    "APIKeyResponse",
    "AuditLogResponse",
    "PasswordChange",
    "Token",
    "TokenRefresh",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "UserUpdate",
    "ExecuteSignalRequest",
    "ForceExitRequest",
    "PortfolioStateDetailResponse",
    "PortfolioStateResponse",
    "PositionResponse",
    "RiskDiagnosticsResponse",
    "StartSessionRequest",
    "TradeResponse",
    "TradingSessionResponse",
    "BacktestArtifactResponse",
    "BacktestComparisonEntry",
    "BacktestComparisonResponse",
    "BacktestComparisonSummary",
    "BacktestDecisionLogEntry",
    "BacktestEquityPointResponse",
    "BacktestExportResponse",
    "BacktestMetricsResponse",
    "BacktestParameters",
    "BacktestRunDetailResponse",
    "BacktestRunResponse",
    "BacktestTradeLogEntry",
    "StartBacktestRequest",
]
